### ISSUE TITLE
About flow-extras

### ISSUE THREAD

**Issue by Lazerbeak12345** [luk3yx/minetest-flow#10]
By the way, if you'd like to migrate anything from my flow-extras library, I'm 100% ok with that library being used as a sort of testing lib for what might be up-streamed here.

In the migration process, I don't even think it needs to be perfectly compatible either. I see the library as things I _might_ like in flow, but could complicate the library more than needed. There's also the possibility that some widgets won't be useful in the real world.

As of right now, I don't know that there's much of value to be in flow, but I'll be playing around with searching iterators for my next feature update. These might be genuinely useful - but I'd wait till they've had real use. As you might have inferred the whole "mods modding form-providing mods" scenario is quite complicated - and my numerous attempts (more than 6 so far) to fix the problem are indicative of ... something.

PS: you can close this when done.
PPS: If you look at my recent minetest related repos you can find my sway-inv-plus repo. That repo is dedicated _entirely_ to throwaway code that might be used in the "real world" for the mod. If you need examples anyway.

**Comment by luk3yx** [comment]
Thanks! I'd like to add something like `flow_extras.Grid` someday, though I'd have to figure out what the API would look like and whether column/row span options are necessary (they sound hard to implement).

> I'll be playing around with searching iterators for my next feature update.

That sounds really interesting, I'm looking forward to seeing how it works.

**Comment by Lazerbeak12345** [comment]
If you didn't notice, that update was released (version 1.3). The relevant function is `flow_extras.search`.
