### ISSUE TITLE
feature-request: max_(w, h, expand)

### ISSUE THREAD

**Issue by Lazerbeak12345** [luk3yx/minetest-flow#12]
I've found in some edge cases it might be useful to force the contents of a given hbox or vbox within certain bounds.

- `max_w`
- `max_h`
- `max_expand` (might not be needed, especially since `max_w` and `max_h` could cover this)

In particular, I've gotten user complaints that the size of sway (my inventory mod using flow) changes too much. This could greatly help with that.

This would only apply to all expandable elements. `gui.Spacer{ expand = true, max_expand = 20 }` could be useful.

Example:

```lua
gui.HBox{
    gui.VBox{
        gui.Label{ label = "hi" },
        gui.Spacer{ expand = true, max_expand = 3 },
        gui.Label{ label = "hi" }
    },
    gui.HBox{
        gui.Label{ label = "hi" },
        gui.Label{ label = "hi" },
        gui.Label{ label = "hi" },
        gui.Label{ label = "hi" },
    }
}
```

This will ensure that the bottom text row on the left column is never more than 3 units below the first row, but could be as few as 0.

Serves as a natural counterpart to `min_w` and `min_h`.

I've also considered cases like this:

```lua
gui.HBox{
    gui.VBox{
        ...
        max_h = 3,
        max_w = 4
    },
    ...
}
```

All of the above would be useful for creating layouts with a consistent look & feel while still being dynamic.

**Comment by luk3yx** [comment]
> In particular, I've gotten user complaints that the size of sway (my inventory mod using flow) changes too much. This could greatly help with that.

Do you have any screenshots (or an example of where this is a problem)? I'm curious to see what sway looks like and to figure out why using `expand = false` and setting a large enough `min_w` and `min_h` (or just manually setting the width if it's a label/button) wouldn't work instead.

And what would happen if it's impossible to fit all the contents of the VBox without going over `max_w`/`max_h`? Would `align_h = "fill"`/`align_v = "fill"` ignore `max_w`/`max_h`?

```lua
gui.VBox{
    max_h = 2,
    gui.Image{w = 1, h = 1, texture_name = "air.png"},
    gui.Image{w = 1, h = 1, texture_name = "air.png"},
    gui.Image{w = 1, h = 1, texture_name = "air.png"},
}
```

**Comment by Lazerbeak12345** [comment]
I'll get back to you on most of this (I'll show you some cursed scenarios I've created/discovered, with bgcolors set so I can explain what's going on).

The biggest reason why this part:

> `expand = false` and setting a large enough `min_w` and `min_h` (or just manually setting the width if it's a label/button)

wouldn't work is in the case of mods modding mods. Changing those things is _very_ difficult on the fly without massive performance drawbacks - even though it _is_ possible.

> And what would happen if it's impossible to fit all the contents of the VBox without going over `max_w`/`max_h`?

I'd imagine that in the short-term, you (as in the maintainer of flow itself) would pick an overflow behavior, likely one from CSS that would fit best in the cases identified. Long-term, we could add multiple overflow behaviors/modes.

Of import is that we can't cut off text on a per-pixel basis. This would eliminate nearly all forms of cutting things off, aside from just removing the node. One could perform some string trimming, so long as #4 is accounted for, and partial Unicode characters aren't left behind. Sounds quite complicated and very slow to me. Image trimming should also be doable using image operations and stuff.

My current recommendation: when calculating the size of each child, if that child overflows, remove it (and all following siblings), then stop calculating the size.

> Would `align_h = "fill"`/`align_v = "fill"` ignore `max_w`/`max_h`?

Not sure what you mean, but in this case I think I can justify a specific behavior. Aligned items would never align in a way that would make their parent larger than the `max_w` or `max_h`, with possible exceptions around overflowing. (Ofc, the "base" max_w would just be the "infinite" value)

**Comment by Lazerbeak12345** [comment]
I changed my mind - I don't think I need this anymore. Feel free to re-open it if you feel otherwise, ofc!
