### ISSUE TITLE
Size of translatable text should be determined after (not before) translation.

### ISSUE THREAD

**Issue by Lazerbeak12345** [luk3yx/minetest-flow#4]
`get_lines_size` should use a server-side translation to get the actual line size.

Problem: server side translations require information about the player that the formspec is getting sent to. `minetest.get_translated_string(lang_code, string)`, where `lang_code` can be retrived from `minetest.get_player_information(name)`. Likely solution would  be to pass that down somehow?

There are a few places, like in `gui.PaginatedVBox`, for example, where this information would be unavailable. Fallback to current behavior should be fine.

**Comment by luk3yx** [comment]
Lua's length operator uses the size of the text in bytes so labels would be too wide if they had lots of non-ASCII characters.
